/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kubeek_device_k2screendevice_K2Screen */

#ifndef _Included_com_kubeek_device_k2screendevice_K2Screen
#define _Included_com_kubeek_device_k2screendevice_K2Screen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_close
  (JNIEnv *, jobject);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    plot
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_plot
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    plotAll
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_plotAll
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    _plot
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen__1plot
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_update
  (JNIEnv *, jobject);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    fade
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_fade
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    setBright
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_setBright
  (JNIEnv *, jobject);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    plotLine
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_plotLine
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    plotCircle
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_plotCircle
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    plotEllipseRect
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_plotEllipseRect
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    plotBasicBezier
 * Signature: (IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_plotBasicBezier
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    _putChar
 * Signature: (IICLjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen__1putChar
  (JNIEnv *, jobject, jint, jint, jchar, jstring, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    putChar
 * Signature: (IICLjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_putChar
  (JNIEnv *, jobject, jint, jint, jchar, jstring, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    scrollText
 * Signature: (ILjava/lang/String;Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_scrollText
  (JNIEnv *, jobject, jint, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     com_kubeek_device_k2screendevice_K2Screen
 * Method:    scrollPPM
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_kubeek_device_k2screendevice_K2Screen_scrollPPM
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
